language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3

os: linux

matrix:
    include:
        - os: osx
          language: generic

addons:
    apt:
        packages:
            - libxml2
            - libxslt

install:
    - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        export RUN_COVERAGE=true;
        pip install coverage codecov;
      fi &&
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew install libxml2 libxslt;
      fi &&
      pip install nose lxml

script:
    - if [[ $RUN_COVERAGE == true ]]; then
        nosetests --with-coverage test/ && codecov;
      else
        nosetests test/;
      fi
